name: 'Houdini Main Changelogs Internal Action'
description: 'Action to publish daily patch reports'
inputs:
  bot-token:
    description: 'Telegram bot token'
    required: true
  chat-id:
    description: 'Telegram chat ID or @username'
    required: true
  config-dir:
    description: 'Where search file houdini_main_changelogs.last_id'
    required: true
outputs:
  last-id:
    description: 'last read id'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/sergeysova/this_week_in_rust.rs/main'
  # image: 'Dockerfile'
  entrypoint: /app/bot
  env:
    BOT_TOKEN: ${{ inputs.bot-token }}
    CHAT_ID: ${{ inputs.chat-id }}
    CONFIG_DIR: ${{ inputs.config-dir }}
